### ISSUE TITLE
Mod breaks upgrade and ship buying menus

### ISSUE THREAD

**Issue by M-Thing** [DeadAirRT/deadairfactionamarr#2]
Hello! I am not sure where else to report bugs, redirect me if there is a better location, please!

While running through the game's tutorials, I noticed that the ship upgrades menu was broken. The ship render would still appear and I could rotate, pan, zoom, etc. but none of the UI is present, completely gone. I did some further testing and the purchasing ships menu is also completely black! 

I do have other mods installed (Including your other faction mods!), but I managed to isolate it to only the Amarr faction mod. The bug occurs regardless of what other mods are installed or enabled. Generating a new game does not seem to have issues. I also noticed that none of the new Amarr ships are listed when starting a creative mode game despite ships added by other mods appearing.

Thank you for the mods!

**Comment by DeadAirRT** [comment]
Double check the folder names. If you download from the code section, github adds -master to the folder name. It is best to grab the zip from releases section.

**Comment by M-Thing** [comment]
I had already removed the -main that github adds to. I however did try installing the release version of Amarr and it fixed the issue! But now none of the new factions' ship models load in. The ships seem to be fully functional and capable of movement, but everything except added modules is invisible. I am now completely unsure how to replicate my original issue and have no idea what is causing this new issue!

**Comment by M-Thing** [comment]
I am dumb and have found your forum thread where you have stated that the ship textures need to be updated. Thank you for the quick reply!

**Comment by DeadAirRT** [comment]
Glad to help, I uploaded the new versions and will package releases soon.
